name: mandrill
version: 1.1.2
description: An unofficial but maintained API client for the Mandrill email as a service product.
environment:
  sdk: ">=1.8.0 <3.0.0"
authors:
- Matias Meno <matias.meno@exit.live>
homepage: https://gitlab.com/exitlive/mandrill-dart
dependencies:
  codable: ^1.0.0
  meta: ^1.1.6
  http: ">=0.11.0 <0.13.0"
  intl: ^0.16.1
  logging: ^0.11.0
dev_dependencies:
  test: ^1.3.0
  mockito: ^4.0.0
  grinder: ^0.8.3
  grind_publish: ^0.0.5
